[phases.setup]
nixPkgs = ["nodejs", "ffmpeg", "python3", "make", "gcc", "pkg-config"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = ["npm rebuild --build-from-source"]